name: cellprofiler

channels:
- conda-forge
- anaconda
- bioconda
- defaults
- pytorch
- nvidia

dependencies:
- python
- pytorch
- torchvision
- torchaudio
- cuda
- opencv
- pip
- numpy>=1.23.0
- matplotlib
- pandas
- mysqlclient
- openjdk
- scikit-learn
- mahotas
- python-javabridge
- Jinja2>=3.0.1
- inflect>=5.3.0
- wxPython
- mysqlclient>=1.4.4
- sentry-sdk>=0.18.0
- ipykernel
- pytorch-cuda=12.1
- tensorflow
- cudatoolkit
